#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

message="$(cat $1)"
requiredPattern="(feature|fix|refactor|deps|docs|test)[[:space:]]+#[0-9]+:[[:space:]]+[A-Za-z ]+$" 
if ! [[ $message =~ $requiredPattern ]];
then
  echo "-"
  echo "🚨 Wrong commit message! 😕"
  echo "-"
  echo "The commit message must have this format:"
  echo "<commit type> <issue number>: <what was done>"
  echo "Available commit types: feature, fix, refactor, deps, docs or test"
  echo "Example: feature #1: some message"
  echo "-"
  echo "Your commit message was:"
  echo $message
  echo "-"
  exit 1
fi